mod audit;
mod bench;
mod compact;
mod daemon;
mod info;
mod keygen;
mod serve;
mod submit;
mod sync;

pub use audit::run as audit;
pub use bench::run as bench;
pub use compact::run as compact;
pub use daemon::run as daemon;
pub use info::run as info;
pub use keygen::run as keygen;
pub use serve::run as serve;
pub use submit::run as submit;
pub use sync::run as sync;

pub fn usage() {
    eprintln!(
        "Usage:
  zamsync info    <data-dir>
  zamsync submit  <data-dir> <payload> [--schema none|json|json+f1,f2]
  zamsync sync    <data-dir> <peer-addr> <peer-id> [--tls] [--schema ..] [--metrics <addr>]
  zamsync serve   <data-dir> <bind-addr> [--tls] [--schema ..] [--policy all|own] [--metrics <addr>]
  zamsync daemon  <data-dir> <peer-addr> <peer-id> [--tls] [--schema ..] [--interval <secs>] [--metrics <addr>]
  zamsync compact <data-dir>
  zamsync keygen  <data-dir>
  zamsync bench   <data-dir> [--events N]
  zamsync audit   <data-dir> [--format json|text] [--since <unix-ms>] [--node <id>] [--key-file <path>]

Flags (serve / sync / daemon):
  --tls              Use mTLS with credentials in <data-dir>/tls/
  --interval <secs>  Sync interval for daemon mode (default: 60)
  --metrics <addr>   Expose Prometheus /metrics on <addr> (e.g. 0.0.0.0:9090)

Flags (all commands that open the WAL):
  --key-file <path>  Decrypt WAL with key at <path> (generated by keygen)
  --schema <mode>    Payload validation: none (default), json, json+field1,field2
  --policy <mode>    Access policy (serve only): all (default), own (peer gets only its own events)"
    );
}
